[workspace]
resolver = "2"
members = ["runner", "kernel", "kernel/crates/*"]
exclude = []

[profile.dev]
# Unoptimised Rust is so chonky that it will absolutely overflow any reasonably sized stack. Do a
# bare minimum amount of optimisation so that our stacks can be "small".
opt-level = 1
