[package]
name = "buddy-alloc"
version = "0.1.0"
edition = "2021"

[features]
cli = ["dep:opener"]

[dependencies]
bitvec = { version = "1.0.1", default-features = false }
num = { path = "../num" }
opener = { version = "0.6.1", optional = true }
